### ISSUE TITLE
Happn blink with email protection

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/services-all#370]
The following [change](https://github.com/ambanum/OpenTermsArchive-versions/commit/31c845df259b2be18024b20a928bb010d65940fe) occurs regularly and affects the quality of the recorded versions.

My investigations did not allow me to find the origin of the problem.

**Comment by martinratinaud** [comment]
See https://github.com/ambanum/OpenTermsArchive-versions/commits/master/happn/Terms%20of%20Service.md for details

I suggest to make a one time specific filter to remove this (See my above commit and branch)

This filter might be used on other services though and might be to be put in the common filters
