### ISSUE TITLE
Add Grindr - Privacy Policy

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/services-all#48]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/en/contribute/service?documentType=Privacy%20Policy&name=Grindr&selectedCss[]=.content&step=2&url=https%3A%2F%2Fwww.grindr.com%2Fprivacy-policy%2F%3Flang%3Den-US&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Grindr",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://www.grindr.com/privacy-policy/?lang=en-US",
      "select": [
        ".content"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Grindr.json`

**Comment by clementbiron** [comment]
Grindr is now tracked in `dating` subset https://github.com/OpenTermsArchive/services-dating/blob/main/declarations/Grindr.json
