### ISSUE TITLE
Add Badoo - Privacy Policy

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/services-all#49]
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://opentermsarchive.org/en/contribute/service?documentType=Privacy%20Policy&name=Badoo&selectedCss[]=.formatted-text&step=2&url=https%3A%2F%2Fbadoo.com%2Fprivacy%2F&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Badoo",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://badoo.com/privacy/",
      "select": [
        ".formatted-text"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Badoo.json`

**Comment by clementbiron** [comment]
Badoo is now tracked is `dating` subset: https://github.com/OpenTermsArchive/services-dating/blob/main/declarations/Badoo.json
